sudo: false

services:
- memcached

language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9

cache: pip

env:
  matrix:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1
  - DJANGO=3.2
  - DJANGO=master

matrix:
  fast_finish: true
  include:
  - env: TOXENV=flake8
    python: 3.9
  - env: TOXENV=isort
    python: 3.9
  - env: TOXENV=twine
    python: 3.9
  - env: TOXENV=check-manifest
    python: 3.9
  allow_failures:
  - env: DJANGO=master

install:
- travis_retry pip install -U pip setuptools tox-travis wheel
script:
- tox

deploy:
  provider: pypi
  user: Surgo
  password:
    secure: xTH+KGdqjWwUgp1ElrEsOtt855k6VwR1UHedMj90ge3jNmYD49o02yPbRTgyOkSJ8ONs79rYbGqPzcm3RYVYHHAWF0pv8pAc4wl9wYZe5AL0VqhJEz3bdpz4CXViwKyF7oABV2N77ALEKJfHbuBLe5kC74NfMuDnVASP+44J1s8=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: django-pymemcache/django-pymemcache
    python: 3.9
    condition: $DJANGO=3.2
